name: E2E Test
on: 
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  e2e:
    name: End to End tests
    timeout-minutes: 30

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: npx playwright install --with-deps && npx @replayio/playwright install

      - name: Run your tests
        run: pnpm e2e-react-replay

      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.3
        with:
          api-key: rwk_zc9H1fCMI0B9mMJxY8wYE5vQOQ2FEnBu9ohGb5OMH10