name: E2E Test
on: 
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:

env:
  CI: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  playwright-record:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: npx playwright install --with-deps && npx @replayio/playwright install

      - name: Run your tests
        run: pnpm e2e-react-replay
        env:
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}

      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.3
        with:
          public: true
          api-key: rwk_zc9H1fCMI0B9mMJxY8wYE5vQOQ2FEnBu9ohGb5OMH10
  playwright-no-record:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: npx playwright install --with-deps && npx @replayio/playwright install

      - name: Run your tests
        run: pnpm e2e-react-replay
        env:
          RECORD_REPLAY_NO_RECORD: 1
          RECORD_REPLAY_TEST_METRICS: 1
          RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
  playwright-original:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run your tests
        run: pnpm e2e-react
